on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      - run: |
          apt-get update && \
          apt-get install -y \
          build-essential \
          bwidget \
          libcairo2-dev \
          libcurl4-gnutls-dev \
          libexif-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libgdal-dev \
          libgeos++-dev \
          libgeos-dev \
          libglib2.0-dev \
          libgmp3-dev \
          libgsl0-dev \
          libmagick++-dev \
          libproj-dev \
          libspatialite-dev \
          libssh2-1-dev \
          libssl-dev \
          libtiff5-dev \
          libudunits2-dev \
          libxml2-dev \
          libxt-dev \
          make \
          netcdf-bin \
          pandoc \
          pandoc-citeproc \
          zlib1g-dev
      - run: |
          echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
      - run: |
          Rscript -e 'install.packages("remotes"); remotes::install_deps(upgrade = "never"); rmarkdown::render(input = "R/analysis.Rmd", params = list(show_results = TRUE), output_file = "analysis-rendered-in-githubactions.html"); rmarkdown::render(input = "main-script.Rmd", output_file = "paper-rendered-in-githubactions.docx")'
      - name: Upload results
        uses: actions/upload-artifact@main
        with:
          name: results
          path: |
            paper-rendered-in-githubactions.docx
            R/analysis-rendered-in-githubactions.html
