language: bash

services:
  - docker

script:
  - make docker_build

env:
  global:
  - REPO={{{USER}}}/{{{REPO}}}

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - export REPO={{{USER}}}/{{{REPO}}}
  - if [ $TRAVIS_BRANCH == "main" ]; then docker push $REPO; fi
