# Change the word USER by your DockerHub username
env:
  global:
  - DOCKERHUB_USERNAME=USER

os: linux
dist: xenial

language: shell

services:
  - docker

script:
  - make docker_build

after_success:
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then \
        docker login --username $DOCKERHUB_USERNAME --password "$DOCKERHUB_PASSWORD"; \
        make docker_push; \
    fi
