os: linux
dist: xenial

language: shell

services:
  - docker

script:
  - make docker_build

after_success:
  - docker login -u {{{USER}}} -p "$DOCKER_PASSWORD"
  - export REPO={{{USER}}}/{{{REPO}}}
  - if [ $TRAVIS_BRANCH == "main" ]; then docker push $REPO; fi
